[module]
  [module.hugoVersion]
    extended = true
    min = "0.62.0"

[params]
  defaultTheme = "auto"
  gitRepo = ""
  fingerprint = ""
  dateFormat = "2006-01-02"
  title = "My cool site"
  description = "This is my cool site"
  images = []

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "My cool site"
      pre = ""
      post = ""
      typeit = false

  [params.footer]
    enable = true
    custom = ""
    hugo = true
    copyright = true
    author = true
    since = 2022
    icp = ""
    license= ""

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.app]
    title = "My cool site"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  [params.search]
    enable = false
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = ""
      title = ""
      subtitle = "This is my cool site"
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = ""
    Linkedin = ""
    Twitter = ""
    Instagram = ""

[params.page]
  hiddenFromHomePage = false  # Hide article from homepage?
  hiddenFromSearch = false  # Hide article from search?
  twemoji = false  # Use twemoji?
  lightgallery = false  # Use lightgallery?
  ruby = true  # Use ruby extended syntax?
  fraction = true  # Use fraction extended syntax?
  fontawesome = true  # Use fontawesome extended syntax?
  linkToMarkdown = true  # Show link to raw Markdown content?
  rssFullText = false  # Display full text in RSS?

  # Table of Contents Config
  [params.page.toc]
    enable = true  # Use table of contents?
    keepStatic = false  # Maintain static TOC at article front?
    auto = true  # Automatically expand/collapse sidebar TOC?

  # Code Config
  [params.page.code]
    copy = true  # Display copy button on code blocks?
    maxShownLines = 50  # Default expanded code line count

  # KaTeX Config
  [params.page.math]
    enable = false
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    copyTex = true  # KaTeX extension: copy_tex
    mhchem = true  # KaTeX extension: mhchem

  # Mapbox Config
  [params.page.mapbox]
    accessToken = ""  # Mapbox GL JS access token
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    navigation = true
    geolocate = true
    scale = true
    fullscreen = true

  # Social Sharing Config
  [params.page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    # ... (continued as per given)

  # Comment Systems Config
  [params.page.comment]
    enable = false
    [params.page.comment.disqus]
      enable = false
      shortname = ""
    # ... (continued for other comment systems)

  # Third-party Libraries
  [params.page.library]
    [params.page.library.css]
      # Example: someCSS = "some.css"
    [params.page.library.js]
      # Example: someJavascript = "some.js"

  # Page SEO Config
  [params.page.seo]
    images = []
    [params.page.seo.publisher]
      name = ""
      logoUrl = ""

# TypeIt Config
[params.typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "|"
  duration = -1

# Site Verification
[params.verification]
  google = ""

# Site SEO Config
[params.seo]
  image = ""
  thumbnailUrl = ""

# Analytics Config
[params.analytics]
  enable = false
  [params.analytics.google]
    id = ""
    anonymizeIP = true

# Cookie Consent
[params.cookieconsent]
  enable = false
  [params.cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# CDN Config
[params.cdn]
  # Example data file: ["jsdelivr.yml"]
