# This is a Workflow Configuration file used for building and deploying a Hugo site to GitHub Pages
# This workflow sets up the necessary environment, builds a Hugo site, and then deploys it to GitHub Pages. 
# It's designed to run on pushes to the master branch or when manually triggered
name: Deploy Hugo site to GitHub Pages

on:
  # The workflow will run when there's a push to the "master" branch
  push:
    branches: ["master"]

  # Allows the workflow to be triggered manually from the GitHub Actions tab in the repository
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read  # The GITHUB_TOKEN can only read repository contents
  pages: write    # The GITHUB_TOKEN can write to GitHub Pages
  id-token: write # The GITHUB_TOKEN can write id-tokens

# Ensures only one deployment job runs at a time, but doesn't cancel any in-progress runs.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Sets the default shell to bash for all the run commands in this workflow
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest # Specifies the runner type. Here we're using the latest version of Ubuntu
    env:
      HUGO_VERSION: 0.119.0 # We define environment variables like the HUGO Version
    steps: # List of the sequential tasks to be executed
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout the code from the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build the site using Hugo
        env: # We define the deployment environment and its URL
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload the built site as an artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest # Specifies the runner type. Here we're using the latest version of Ubuntu
    needs: build # Specifies that the deploy job requires the build job to be successful
    steps:
      - name: Deploy the site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
